name: pig_server
version: 0.0.1
description: Pigation Server
repository: https://github.com/bsutton/pig_server
publish_to: none
environment:
  sdk: '>=3.3.0 <4.0.0'
dependencies:
  acme_client:
    hosted: https://onepub.dev/api/jbbxpsdavu/
    version: ^1.3.0
  archive: any
  args: ^2.4.2
  collection: ^1.19.1
  cron: ^0.6.0
  dart_periphery: ^0.9.12
  date_time_format: ^2.0.1
  dcli: ^6.0.5
  dcli_core: ^6.1.0
  dnsolve: ^1.0.0
  email_validator: ^3.0.0
  fixed: ^5.2.0
  http_parser: ^4.0.2
  intl: ^0.19.0
  mailer: ^6.0.1
  mime: ^1.0.4
  mime_type: ^1.0.0
  path: ^1.9.0
  pig_common:
    path: ../pig_common

  pointycastle: ^3.9.1
  sentry: ^8.12.0
  settings_yaml: ^8.1.0-alpha.2
  shelf: ^1.4.1
  shelf_letsencrypt:
    hosted: https://onepub.dev/api/jbbxpsdavu/
    version: ^2.0.0
  shelf_multipart: ^2.0.0
  shelf_rate_limiter: ^1.0.1
  shelf_router: ^1.1.4
  shelf_static: ^1.1.2
  shelf_web_socket: ^2.0.1
  sqflite_common: ^2.5.4+6
  sqflite_common_ffi: ^2.3.4+4
  strings: ^3.1.2
  timezone: ^0.10.0
  web_socket_channel: ^3.0.2


  
dev_dependencies:
  http: any
  lint_hard: ^5.0.0
  mockito: ^5.4.5
  test: ^1.25.14
 
executables:
  pig_server:


