name: pigation
version: 3.0.0
description: Pigation Server - an irrigation system for the Raspberry Pi
repository: https://github.com/bsutton/pig_server
environment:
  sdk: '>=3.3.0 <4.0.0'
dependencies:
  acme_client: ^1.3.0
  archive: ^3.6.1
  args: ^2.4.2
  collection: ^1.19.1
  cron: ^0.6.0
  dart_periphery: ^0.9.12
  date_time_format: ^2.0.1
  dcli: ^6.1.2
  dcli_core: ^6.1.2
  dnsolve: ^1.0.0
  fixed: ^5.3.1
  http_parser: ^4.1.2
  intl: ^0.19.0
  mime: ^2.0.0
  path: ^1.9.0
  pig_common: ^1.0.0

  pointycastle: ^3.9.1
  posix: ^6.0.1
  settings_yaml: ^8.2.0
  shelf: ^1.4.1
  shelf_letsencrypt: ^2.0.1
  shelf_rate_limiter: ^1.0.1
  shelf_router: ^1.1.4
  shelf_static: ^1.1.2
  shelf_web_socket: ^2.0.1
  sqflite_common: ^2.5.4+6
  sqflite_common_ffi: ^2.3.4+4
  strings: ^3.1.2
  timezone: ^0.10.0
  web_socket_channel: ^3.0.2


  
dev_dependencies:
  http: any
  lint_hard: ^5.0.0
  mockito: ^5.4.5
  pub_release: ^11.2.0
  pubspec_manager: ^1.0.1
  test: ^1.25.14
 
executables:
  pig:


